# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kTKT+WBnbLHm+MxqZQXmuoYprJWSDwZpIj78R5UUFbOpB0OcwJfdViPSHQJOYB/TkCVG+on/V4mh1kyQ/gzVaQopWUK0auV146C1vTuKVLtFpqP6z3EMBL7nULKb/z6WnM+KOw3P74i6nDfJ04XlOH2gt1pnMUDs6V8rJm8j1M42uwFRu/u4EebP/IRJlxFkKqQIywF5XwoclJuTIGoeh5U3W4q9/mIvHf4DEO8+x2RS1ui38LxcH29YfexmlJm9OqCSn98YCz05vYxLkHdmUexqhozENLQZAlr8rKo3elWSRQtR73bbj6vIlukLjVsp2flZBlQ8q1UseeU/v9UKGeM74VdbuZqXgSVETXNAIVkz11x5pmtRZYesSeJlnyZNUhAPZVDWFbA7MDj+WobdnHD/45OpOx5KiPo+bOgW+KqWr3b7btH9W9na1/IUjgfzx+4LORWJh4QdP0EmNTj96b9ibJVRENiEIGRDj8OTupF0A74ewARboNkrcbfqcqHRQpUZa9T/MEKIuYsgMiPAcByt21jCeU0Mxc5Tnbv0vQ7qbSYZxQDzeEqGLzdPq8Dw+VEsq/xLi3lcWT+kLWNs1wMs7RjPUTUZlV4LEPmjZgTnHv+1FHHpJviEvojf09x+b52WpUx4Zz7Xa91tp2lrq8O38a26egKK8hTDtxHMcY8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
