travis:
  secure:
    BINSTAR_TOKEN: Ro9Q0lCmFHLb/oBaT/WVCq1qKkmqjIJ7mCg/9nSJIFtHDFDCzAzMQ/m2fpp0cSWsqbMUa46rZzg3fF8I07JT0f6rUlwikNtsefETjR3LgCkkqaMO5HCpqCtvM/lnQZXKWoaKY0q/xSX2H9NRd/ye5hX07NYwPA7PR9/NpjJzUPBkRHFlLDFBJR+ti25fmGoRO262ycotci/RP2CDqJd+vyiWIpJN5OkQssRq1XGbbgEWf5bz36SkYUTplOIByBo+MTe7PRAloj427ORT2NAcruKNjDEM+9yl2a0wouAeAdp7aBLjFCRTPl+q7DjP08a669B05RAQfFTE/biWFrvA/J/01D3qDdhP+Ri3TlWqml8cz37WKrx6ipKaPALMp46w1glijKxCcU3JZbDQPuXGW0w2+/4iMCc9FEaTdM9klnwPSNQoqTAV/lQxjJIVHc2r+0K34lIO5GlReSSMoS0KCoghOaLcJRPMBDQxcx5QZCokKjRSni32a1i/Fi29yQLMXn5RjIN/KquueGHwuyIhUiy2vDCQfSvK/0V4HZmljZloKQt/ziZ+sIwUaTd9/8l8poln9ZsGfMOxRKgR9Ylb1pqBKmlHCiTgCb6fSZVPVDq+crpcRh0fH2HfklkGQ/+LUmOs+uiVcWUFLfSefG3If67A+3xqsHRSNxGVXTrUzp0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
