travis:
  secure:
    BINSTAR_TOKEN: kTKT+WBnbLHm+MxqZQXmuoYprJWSDwZpIj78R5UUFbOpB0OcwJfdViPSHQJOYB/TkCVG+on/V4mh1kyQ/gzVaQopWUK0auV146C1vTuKVLtFpqP6z3EMBL7nULKb/z6WnM+KOw3P74i6nDfJ04XlOH2gt1pnMUDs6V8rJm8j1M42uwFRu/u4EebP/IRJlxFkKqQIywF5XwoclJuTIGoeh5U3W4q9/mIvHf4DEO8+x2RS1ui38LxcH29YfexmlJm9OqCSn98YCz05vYxLkHdmUexqhozENLQZAlr8rKo3elWSRQtR73bbj6vIlukLjVsp2flZBlQ8q1UseeU/v9UKGeM74VdbuZqXgSVETXNAIVkz11x5pmtRZYesSeJlnyZNUhAPZVDWFbA7MDj+WobdnHD/45OpOx5KiPo+bOgW+KqWr3b7btH9W9na1/IUjgfzx+4LORWJh4QdP0EmNTj96b9ibJVRENiEIGRDj8OTupF0A74ewARboNkrcbfqcqHRQpUZa9T/MEKIuYsgMiPAcByt21jCeU0Mxc5Tnbv0vQ7qbSYZxQDzeEqGLzdPq8Dw+VEsq/xLi3lcWT+kLWNs1wMs7RjPUTUZlV4LEPmjZgTnHv+1FHHpJviEvojf09x+b52WpUx4Zz7Xa91tp2lrq8O38a26egKK8hTDtxHMcY8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
